"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import { APIClient } from '../utils/keelClient';
import { keel } from '@teamkeel/client-react';


export const { KeelProvider, useKeel } = keel(APIClient);

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <KeelProvider baseUrl='https://staging--keel-nextjs-auth-demo-wFTfCx.keelapps.xyz/api/'>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </KeelProvider>

  )
}
