"use client"


import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { KeelProvider } from '@/utils/keelContext'

const inter = Inter({ subsets: ['latin'] })





const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <KeelProvider baseUrl='https://staging--keel-nextjs-auth-demo-wFTfCx.keelapps.xyz/api/'>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </KeelProvider>
  )
}
